### ISSUE TITLE
HTTP Error 405: Method Not Allowed

### ISSUE THREAD

**Issue by HagarViking** [ljskatt/nrk-dl#3]
Hva tilsier denne feilmeldingen?

WARNING: Could not send HEAD request to https://tv.nrk.no/se?v=DVSF65100321: HTTP Error 405: Method Not Allowed

**Comment by ljskatt** [comment]
Jeg ser ikke ut til å kunne replikere feilen.
API'et til NRK lever litt sitt eget liv, fungerer det igjen nå?
Gjerne spesifiser hvilke parametere som er brukt og hvilket OS

Lukker issue om det ikke kommer noe mer info

**Comment by ljskatt** [comment]
Lukket grunnet manglende info
